### ISSUE TITLE
welcoming messages

### ISSUE THREAD

**Issue by kermoshina** [deltachat/interface#25]
Testers criticized current welcoming messages ("powerful", "fast" and so on). The big question is: **Do we keep them?** 

If we keep them, I suggest that we:

- Remove a few (e.g. "powerful", "independent", "trustworthy")
- Change the order (e.g. put "encrypted" earlier)
- Put "decentralized" instead of "independent"
- Change the phrasing and pictures

If we decide to remove these screens, we can:

- move some of these explanations to the FAQ and make the FAQ accessible from the login screen (see issue #24)
- add the Delta Chat logo (or another nice graphic) on the login screen

**Comment by comradekingu** [comment]
Powerful and fast is implied, and is not qualified anyhow. It is like saying "trustworthy".

"**Free and independent**" leaves free superfluous, as it is dependent on, and therefore does not communicate anything beyond the stated "**independent**". In the sense that it does, in the sense of _free software_, that realization is predicated on the very knowledge it conveys. When it requires the very prior knowledge it is predicated on conveying it is pointless communication.

To explore further, "**Free software**" has a duality in also possibly meaning gratis, if not for the technical point of invoking freeware as the true "gratis" variant. As "Freeware" has fallen out of fashion, its use as a descriptor equally so. Descriptive validity is lacking for both, and not about to change. Additionally "Free software" has a negative connotation in being mentally tied to the Free Software Foundation (FSF) of late.

"**Libre**" is a better word, and in the case of Delta Chat, _**copylefted libre software**_. "**Open Source**" "Open source" "Open-source" or "Open-Source" is for reasons libre is libre, a meaningless term. Though meaningless, a trademark stands between it and claiming it is null and void. Failing to guess which one it is, this exercise even becomes actively ambiguous in any other language.
Delta Chat is translated, so that one is out. It is very possible to use the direct equivalent of "Free software" in languages that make the aforementioned distinction between gratis and free (as in free speech/freedom/liberty, without any such fitting appendage). However the direct equivalent of "open source", alas something that isn't **OSI-open-source**, fails to separate Delta Chat from the likes of Vivaldi, or the old MAME license. Which respectively are only-open, and non-commercial. Narrowing down the Venn diagram to the exclusivity of what makes Delta Chat great, is both beneficial and meaningful, stopping at nothing other than selling Delta Chat short.

**Decentralized vs. independent** begs the question of what the latter is meant to entail. As it encroaches a far wider set of qualities, I think it is better, and is a standard to hold Delta Chat to, serving as a motivational slogan.
Falling short of not being evil, or being able to champion it with a straight face, gives some credence to having a benefactor slogan.

As for "screens", the way I see it is questioning what it is that is to be accomplished. How many screens, clicks, impressions and navigational questionnaires stands between what that is, and getting it done?

An initial assumption; the user didn't just already install Delta Chat to gauge how powerful and fast it is by spending time looking at said words.
That whole ordeal is neither fast nor powerful. The pudding is in the very least in the pudding on this one. Be powerful by being powerful, be fast by not being slow…?

**Comment by comradekingu** [comment]
So this is now a "this is a free software", _a_ meaning who knows what. Freeware? The end goal seems to be ensuring nobody knows what is what.

If you have to ask if something has value, maybe try to do without it?
The real issue IMO, from (trying not to have) helped people set it up, is the notion of
1. Explaining that it requires an existing e-mail address. This is not clear.
2. Explaining that it needs the existing password for that e-mail address.

This could potentially have been solved in explaining the ethos better beforehand.

Similarly, "corresponding" does away with the idea that just any setup code will do
https://github.com/deltachat/deltachat-android/pull/1125/commits/5feadcc1cf58388ee4a9b19c44f17ee55c1dcd03#diff-4691bafd7791e471b30c492e6f43d65bR488
(it isn't called "Autocrypt Setup Message Code")

https://github.com/deltachat/deltachat-android/pull/1125/commits/1522e0a3d5062df087e7fa95258efc1e6ee07d12  allowing/granting access.

https://github.com/deltachat/deltachat-android/pull/1125/commits/e7e8950302e876d498aeeb250c19a5788e87e3bc#diff-4691bafd7791e471b30c492e6f43d65bR490

Needless complexion, why is "decryption", "key" and similar even in here?

https://github.com/deltachat/deltachat-android/pull/1125/commits/76137501b8305ceb89e1b3b8e2c265830c06e980

How many regular users know what out-of-band means? How many of those will find it welcoming.
