### ISSUE TITLE
Contact/Chat requests

### ISSUE THREAD

**Issue by Jikstra** [deltachat/interface#3]
Android dev & desktop currently only allow to accept the latest "contact/chat request" to be accepted or declined. This stack like procedure isn't really user friendly in my opinion. Some overview over the chat requests would be better in my opinion, maybe one which also allows seeing all the messages in this chat request because currently multiple messages in one chat request aren't getting grouped.

**Comment by r10s** [comment]
an overview is availabe in android using the command "contact requests" from the main menu. there also details about the messages are shown.

internally, the list list just a normal chat that can be easily created using dc_get_chat_list(context, DC_CHAT_ID_DEADDROP);

wrt stacking: i think this is not the worse. otherwise the chatlist may be flooded with unhandled contact requests. so, at least for now, i would not go for changing this.
