### ISSUE TITLE
Signature Handling

### ISSUE THREAD

**Issue by frink** [deltachat/interface#41]
Moved to: https://support.delta.chat/t/email-signature-handling/1292

**Comment by hpk42** [comment]
There already is quoting-support and "swipe-to-reply", recently released.
Do you know about this? 

As to the signatures -- this is for using Delta Chat as e-mail client, i.e.
focused on how the message appears on a non-deltachat side right?

**Comment by adbenitez** [comment]
if you are chatting from Delta Chat with Spike users, you will see the Spike quotes in the delta chat bubbles because Spike uses alternate plain text part which uses quotes incorrectly while the html part shows quotes correctly, the plain text part is used in email clients that disable html, and they are not shown properly as quotes, so it is not a Delta Chat issue, Delta Chat hides quotes correctly replacing them with "[...]" (unless atop or end of message where they are shown as a nice short reply like in other chat apps.
Regards,
adb

**Comment by frink** [comment]
Is there a way to make sure all email gets to DeltaChat. I've only gotten the Delta Chat folder not the rest. Ultimately stopped testing. But I'd like to replace Spike with something that is a little less buggy.

**Comment by adbenitez** [comment]
in Settings go to "Chats and Media" in "Email interaction" change from "chats only" to "all" you will receive all emails as chats messages even id the sender doesn't use Delta Chat 

NOTE: mailing list (github emails, etc) aren't currently supported, but migh come in a near future (peek at the dc core repo, there is a PR)

**Comment by r10s** [comment]
as the issue was moved to  https://support.delta.chat/t/email-signature-handling/1292, closing it here.
